# Generated by Django 4.2.3 on 2023-07-10 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('hobbies', models.CharField(blank=True, max_length=100, null=True)),
                ('profation', models.CharField(blank=True, choices=[('IT', 'IT'), ('financial', 'financial'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Consalting', 'Consalting')], max_length=100, null=True)),
                ('marrid_status', models.CharField(blank=True, choices=[('Married', 'Married'), ('UnMarried', 'UnMarried')], max_length=100, null=True)),
                ('cast', models.CharField(blank=True, max_length=100, null=True)),
                ('subcast', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
